Algoritmo "Questao 11"
//Desenvolva uma lógica que leia os valores de A, B e C de uma equação do
//segundo grau e mostre o valor de Delta

Var

     A,B,C,DELTA:real

Inicio
       escreva("Escreva o valor de A = ")
       leia (a)
       escreva("Escreva o valor de B = ")
       leia (b)
       escreva("Escreva o valor de C = ")
       leia (c)
       
       delta <- b^2 - (4 * a * c)
       
       escreva("OVALOR DE DELTA É = ",delta)




Fimalgoritmo