Algoritmo "Questao 6"
// Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
var
     num1,num2,media: real
inicio
      escreva("Primeira nota. ")
      leia(num1)
      escreva("Segunda nota. ")
      leia(num2)
      media <- (num1+num2)/2
      
      escreval("Nota 1 ",num1:10)
      escreval("Nota 2 ",num2:10)
      escreval("A média entre ",num1, " e ", num2, " é = ",media)

fimalgoritmo

