Algoritmo "Questao 3"
// Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
var
     nome: caractere
     salario: real
inicio
      escreva("Nome do funcionário. ")
      leia(nome)
      escreva("Salário do funcionário. ")
      leia(salario)
      escreval("O funcionário ",nome," tem um salário de ",salario, " R$ em Junho.")

fimalgoritmo